version: '2'

services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/go/src/github.com/hilariousatlantic/mu-scheduler
    depends_on:
      - database
    extends:
      file: base.yml
      service: base

  database:
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - /var/lib/postgresql/data
    extends:
      file: base.yml
      service: base
