version: '2'

services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/go/src/github.com/hilariousatlantic/mu-scheduler
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DBNAME=mu-scheduler
      - POSTGRES_USERNAME=mu-scheduler
      - POSTGRES_PASSWORD=password
