version: '2'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile-go
    ports:
      - 8000:8000
    volumes:
      - ./:/go/src/github.com/hilariousatlantic/mu-scheduler
    depends_on:
      - database
    extends:
      file: base.yml
      service: base

  database:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432"
    volumes:
      - /var/lib/postgresql/data
    extends:
      file: base.yml
      service: base

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - 3000:3000
    volumes:
      - .:/home/mu-scheduler
      - .:/home/mu-scheduler/node_modules
